### ISSUE TITLE
coding

### ISSUE THREAD

**Issue by bladrome** [bruceEeZhao/cciot#2]
It's better to add #-*-coding:utf-8-*- at the first line of your files because when I try to run main.py in command line SyntaxError occurs. ^_^

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from LoginPage import *
  File "/cciot/cclient/LoginPage.py", line 5, in <module>
    from MainPage import *
  File "/cciot/cclient/MainPage.py", line 3, in <module>
    from view import *  # �˵�����Ӧ�ĸ�����ҳ��
  File "/cciot/cclient/view.py", line 5
SyntaxError: Non-ASCII character '\xbc' in file cciot/cclient/view.py on line 5, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by bruceEeZhao** [comment]
use python3.5 to run
